test:
	./testscript

clean:
	make -C elaboration/good clean
	make -C elaboration/bad clean
	make -C inference/good clean
	make -C inference/bad clean
	make -C custom/elaboration/good clean
	make -C custom/elaboration/bad clean
	make -C custom/inference/good clean
	make -C custom/inference/bad clean

