#!/bin/bash

NEUTRAL='\e[0;m'
RED='\e[0;31m'
GREEN='\e[1;32m'

JOUJOU="../src/joujou"

if [ ! -x $JOUJOU  ]
  then
    echo "Joujou executable lacking" 1>&2
    exit 1
fi


GOODE=`find . custom -path '*/elaboration/good/*.mle' | sort`
BADE=`find . custom -path '*/elaboration/bad/*.mle' | sort`

GOODT=`find . custom -path '*/inference/good/*.mlt' | sort`
BADT=`find . custom -path '*/inference/bad/*.mlt' | sort`

echo ".mle fails:"
nbrexpli=0
for f in $GOODE
  do
  OUTPUT=`$JOUJOU $f 2>&1`
  RET=$?
  if [ $RET != 0 ]
    then
      ((nbrexpli++)); 
      echo "$f: $RET"
#      echo "$OUTPUT"
  fi
done

for f in $BADE
  do
  OUTPUT=`$JOUJOU $f 2>&1`
  RET=$?
  if [ $RET != 1 ]
    then
      ((nbrexpli++));
      echo "$f: $RET"
#      if [ -n "$OUTPUT" ]
#        then echo "$OUTPUT"
#      fi
  fi
done

echo ".mlt fails:"
nbrimpli=0
for f in $GOODT
  do
  OUTPUT=`$JOUJOU $f 2>&1`
  RET=$?
  if [ $RET != 0 ]
    then
      ((nbrimpli++));
      echo "$f: $RET"
#      echo "$OUTPUT"
  fi
done

for f in $BADT
  do
  OUTPUT=`$JOUJOU $f 2>&1`
  RET=$?
  if [ $RET != 1 ]
    then
      ((nbrimpli++));
      echo "$f: $RET"
#      if [ -n "$OUTPUT" ]
#        then echo "$OUTPUT"
#      fi
  fi
done

echo

if [ $nbrexpli = 0 ]
 then
    echo -e "Explicit: ${GREEN}$nbrexpli${NEUTRAL} fail\n"
 else
    echo -e "Explicit: ${RED}$nbrexpli${NEUTRAL} fail(s)\n"
fi

if [ $nbrimpli = 0 ]
  then 
    echo -e "Implicit: ${GREEN}$nbrimpli${NEUTRAL} fail\n"
  else
    echo -e "Implicit: ${RED}$nbrimpli${NEUTRAL} fail(s)\n"
fi
